# name: Keep Render API Awake

# on:
#   schedule:
#     - cron: "*/5 * * * *" # Runs every 5 minutes

# jobs:
#   keep_awake:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Ping Render API
#         run: curl -s https://trending-posts.onrender.com
